version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    restart: always

  auth-service:
    build: ./auth-service
    ports:
      - "3002:3002"
    restart: always

  reservation-service:
    build: ./reservation-service
    ports:
      - "3003:3003"
    restart: always

  salle-service:
    build: ./salle-service
    ports:
      - "3001:3001"
    restart: always

  analytics-service:
    build: ./analytics-service
    ports:
      - "3004:3004"
    restart: always
