apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytic-service
  template:
    metadata:
      labels:
        app: analytic-service
    spec:
      containers:
        - name: analytic-service
          image: yosrslama/analytic-service:latest
          ports:
            - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: analytic-service
spec:
  selector:
    app: analytic-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP
